default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mobidic_api_development

test:
  <<: *default
  database: mobidic_api_test

production:
  <<: *default
  database: mobidic_api_production
  username:
  password:
